### ISSUE TITLE
picture.web should ignore resizeMode prop

### ISSUE THREAD

**Issue by sallymew** [raxjs/rax-picture#4]
[https://github.com/raxjs/rax-picture/blob/master/src/picture.web.js#L207](https://github.com/raxjs/rax-picture/blob/master/src/picture.web.js#L207
)

![image](https://user-images.githubusercontent.com/9411153/61097256-33ec9f00-a48d-11e9-94a0-7a4524612e2e.png)

[rax-image](https://github.com/raxjs/rax-image/blob/master/src/index.js#L78) has already handled resizeMode prop

![image](https://user-images.githubusercontent.com/9411153/61097279-51ba0400-a48d-11e9-8626-5cbca1e2a21e.png)

**Comment by recover758126** [comment]
Thanks

**Comment by recover758126** [comment]
The resizeMode can`t be ignored because the rax-image don`t handle the case that component has the children
